# モデル保存ディレクトリ
model_dir: "outputs/train/models"

# 使用するモデル一覧（enable: true のみを使用）
# name は保存済みジョブリブファイルのプレフィックスと一致させてください。
models:
  - name: LinearRegression
    enable: true
  - name: Ridge
    enable: true
  - name: Lasso
    enable: true
  - name: ElasticNet
    enable: true
  - name: SVR
    enable: true
  - name: KNeighbors
    enable: true
  - name: RandomForest
    enable: true
  - name: ExtraTrees
    enable: true
  - name: GradientBoosting
    enable: true
  - name: LightGBM
    enable: true
  - name: XGBoost
    enable: true
  - name: CatBoost
    enable: true
  - name: GaussianProcess
    enable: true
  - name: MLP
    enable: true
  - name: TabNet
    enable: true
  - name: TabPFN
    enable: true
  - name: StackingRandomForest___XGBoost___LightGBM
    enable: true
  - name: VotingRandomForest___XGBoost___LightGBM
    enable: true

# 入力設定
input:
  mode: "params"        # "csv" なら csv_path を指定、"params" なら variables か params_path を指定
  variables:
    - name: age
      type: int
      method: range
      min: 25
      max: 40
      step: 1
    - name: income
      type: float
      method: range
      min: 40000
      max: 80000
      step: 1000
    - name: education
      type: categorical
      method: values
      values: ["Bachelor", "Master"]
  # csv_path: "data/example.csv"  # mode: csv の場合はこちらを記述

# 探索設定
search:
  method: "tpe"        # "grid", "random", "tpe", "cmaes" から選択
  n_trials: 100         # random/tpe/cmaes の試行数
  goal: "min"           # "max" または "min"（目的変数の最大化または最小化）

# 出力設定
output_dir: "outputs/inference"
