data:
  csv_path: "data/example.csv"
  target_column: null
  feature_columns: null
  problem_type: null
  test_size: 0.0
  random_seed: 42

preprocessing:
  numeric_imputation: ['mean']
  categorical_imputation: ['most_frequent']
  scaling: ['standard']
  categorical_encoding: ['onehot']
  polynomial_degree: false

models:
  - name: GaussianProcess
    enable: true
    params:
      kernel: ['RBF']
  - name: MLP
    enable: true
    params:
      hidden_layer_sizes: [64]
      activation: ['relu']
      learning_rate_init: [0.001]
  - name: LinearRegression
    enable: false  # Disabled to speed up the test
  - name: RandomForest
    enable: true
    params:
      n_estimators: [50]

cross_validation:
  n_folds: 5
  shuffle: true
  random_seed: 42

output:
  output_dir: "auto_ml_test_output3"
  save_models: true
  generate_plots: true
  results_csv: "results_test3.csv"

evaluation:
  regression_metrics: ['mae','rmse','r2']
  classification_metrics: ['accuracy']
  primary_metric: null

optimization:
  method: 'grid'
  n_iter: 10

interpretation:
  compute_feature_importance: false
  compute_shap: false

visualizations:
  predicted_vs_actual: true
  residual_scatter: true
  residual_hist: true
  feature_importance: true
  shap_summary: false