data:
  csv_path: "data/example.csv"
  target_column: null
  feature_columns: null
  problem_type: null
  test_size: 0.0
  random_seed: 42

preprocessing:
  numeric_imputation: ['mean']
  categorical_imputation: ['most_frequent']
  scaling: ['standard']
  categorical_encoding: ['onehot']
  polynomial_degree: false

models:
  - name: LinearRegression
    params: {}
  - name: Ridge
    params:
      alpha: [1.0]
  - name: RandomForest
    params:
      n_estimators: [50]

ensembles:
  stacking:
    enable: false
    estimators: []
    final_estimator: null
  voting:
    enable: false
    estimators: []
    voting: null

cross_validation:
  n_folds: 5
  shuffle: true
  random_seed: 42

output:
  output_dir: "auto_ml_test_output"
  save_models: true
  generate_plots: true
  results_csv: "results_test.csv"

evaluation:
  regression_metrics: ['mae','rmse','r2']
  classification_metrics: ['accuracy']
  primary_metric: null

optimization:
  method: 'grid'
  n_iter: 10

interpretation:
  compute_feature_importance: true
  compute_shap: false
